### ISSUE TITLE
Can you release the code of the baseline methods?

### ISSUE THREAD

**Issue by hzy312** [princeton-nlp/MQuAKE#2]
Finetune, rome, memit for main experiments and the batch(mass) editing experiments, PLEASE!

**Comment by sev777** [comment]
> Hi @hzy312 , sorry for the late response!
> 
> We used the [MEMIT](https://github.com/kmeng01/memit) project for all our baselines. Specifically, we run the `experiments.evaluate` module for evaluating baselines on our dataset.
> 
> To enable each sample to have multiple edited facts, you can just modify [this line](https://github.com/kmeng01/memit/blob/main/experiments/evaluate.py#L150) to make sure you pass all the edits to the `apply_algo ` function as a list.

Could you please release the evaluate code for the 'base (Base denotes the model before editing)' results in Table 3? 
![图片](https://github.com/princeton-nlp/MQuAKE/assets/38484725/09c983ad-47da-4ea5-872f-4e114d3918e3)

**Comment by a3616001** [comment]
Hi @sev777 !

Just a note that our MQuAKE-T dataset was updated and now it includes extended gold answer labels that should be used for evaluation before editing. See #6 for more info! Sorry about the bug. (I currently do not have the bandwidth to release the baseline/evaluation code which should be just a minor edit based on MEMIT. But let me know if this doesn't go through!)
